// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Interface.h"
#include "Items/OPWeapon.h"
#include "OPCharacterInterface.generated.h"

// This class does not need to be modified.
UINTERFACE(MinimalAPI)
class UOPCharacterInterface : public UInterface
{
	GENERATED_BODY()
};

/**
 * 
 */
class OUTPOST_API IOPCharacterInterface
{
	GENERATED_BODY()

	// Add interface functions to this class. This is the class that will be inherited to implement this interface.
	
public:
	/*
	Performs a sphere trace, to see if the character's melee attack hit anything. To be used in Animation Notifies only.
	@param	MeleeStart	The location where the sphere trace starts.
	@param	MeleeEnd	The location where the sphere trace ends.
	@param	Radius	The overall width of the melee hitbox.
	@return	An array of all the hit results that were generated by the sphere trace.
	*/
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "OPCharacterInterface|Melee")
		const TArray<FHitResult> MeleeSphereTrace(FVector MeleeStart, FVector MeleeEnd, float Radius);

	/*
	Picks up a weapon, and adds it to the player's inventory.
	@param	NewWeapon	A reference to the weapon that was just picked up.
	*/
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "OPCharacterInterface|Inventory")
		void PickUpWeapon(AOPWeapon* NewWeapon);

protected:
	
};